### ISSUE TITLE
Fuse.Views(Android) shrink content

### ISSUE THREAD

**Issue by jesusmartinoza** [fuse-open/fuselibs#1186] opened 2018-05-23 02:41 UTC
Building Fuse.Views with master 463e5a55fcefd443de1bc5b8015352976f2e1fe1 shrink content of the page

**Issue**
![screenshot_20180522-212549](https://user-images.githubusercontent.com/5506693/40400364-60c16484-5e07-11e8-9d4c-57ecc6140235.jpg)

**Building with 1.8.1(build 15610)**
![screenshot_20180522-214059](https://user-images.githubusercontent.com/5506693/40400686-e7204aa8-5e08-11e8-8c59-a357063ecbb1.jpg)

- Device: Samsung A8(SM-A530F)
- OS: Android 7.1.1

**Comment by kusma** [comment] 2018-05-23 16:12
I think we should bisect this to see when it started happening... I can have a look at that tomorrow.

**Comment by kusma** [comment] 2018-05-24 08:26
Looks like this was caused by #1101. It's still not 100% sure, I'll investigate further.

**Comment by kusma** [comment] 2018-05-24 08:37
Yeah, confirmed to be broken by 6a146d301abd141ad2159a7415300112ce9938fd. Reverting that commit fixes the problem, but that'll re-introduce #1096.

@mortoray: Do you have any thoughts here? This is currently a release-blocker for 1.9...  Is #1096 really that bad?

**Comment by mortoray** [comment] 2018-05-24 08:54
I'd like to see the UX of the screen causing problems, just to ensure it's not one of those odd corner cases that accidentally used an undefined behaviour.

The fix in #1096 can cause certain code to crash, like ManualTestApp. I recall also fixing the bit that crashed as well.  More than likely now 1096 just avoids a duplicate layout cost at startup -- assuming it doesn't trip up any other code.

**Comment by kusma** [comment] 2018-05-24 09:08
@mortoray: It seems that just about *any* UX cause this. Here's my example:

```UX
<App>
  <ExportedViews>
    <StackPanel ux:Template="MyFuseView">
      <Text Value="Fuse.Views test 2000">
              <WhilePressed>
                <Scale Factor="2" />
              </WhilePressed>
      </Text>
      <Text Value="Fuse.Views test 3000">
              <WhilePressed>
                <Scale Factor="2" />
              </WhilePressed>
      </Text>
      <Rectangle Width="100" Height="100" Color="#f0f">
        <WhilePressed>
          <Scale Factor="2" />
        </WhilePressed>
      </Rectangle>
    </StackPanel>
  </ExportedViews>
</App>
```

**Comment by mortoray** [comment] 2018-05-24 09:12
That looks like perhaps an issue in the exportedview bootstrapping then. I think it's safe to revert the other fix then. Duplicate calculations are less problematic than bad layout, and startup time isn't a big complaint I think.

**Comment by kusma** [comment] 2018-05-24 09:14
@mortoray: So, are you saying that reverting 6a146d301abd141ad2159a7415300112ce9938fd seems like a tolerable hot-fix? If so, I'll do that on the release-branch, and reopen the ticket ASAP :)

**Comment by mortoray** [comment] 2018-05-24 09:43
Yes. I've reviewed the patch again and I did isolate just that change -- the thing that was actually crashing was fixed in another patch somewhere.

**Closed** 2018-05-24 10:42 UTC
Labels: Severity: Regression, Severity: Release blocker, Severity: User reported
