### ISSUE TITLE
Camera CRASH

### ISSUE THREAD

**Issue by ckarmy** [fuse-open/fuselibs#1235] opened 2018-10-16 14:13 UTC
This issue still happen! When I try to take a picture the app crash!
https://forums.fusetools.com/t/issue-camera-crash/6391

**Comment by ckarmy** [comment] 2019-01-23 20:41
No updates on this?

**Comment by nekronos** [comment] 2019-01-29 19:57
@ckarmy If you provide a simple repro case I can take a look

**Comment by AndrewEQ** [comment] 2019-01-30 05:11
Is this still an issue? ~ https://forums.fusetools.com/t/issue-camera-crash/6391/26

**Comment by ichan-mb** [comment] 2019-01-30 06:52
Yeah.. i think we need to fix this so user doesn't have to hack, i see maybe we can patch in Uno [here](https://github.com/fuse-open/uno/blob/c31956c32dd6785278884b3b659cbde6d051347a/lib/UnoCore/Targets/Android/app/src/main/AndroidManifest.xml#L2) adding `<provider>` tag, and then [here](https://github.com/fuse-open/uno/tree/master/lib/UnoCore/Targets/Android/app/src/main/res) adding file_paths, lastly patch in Fuselibs Imagetools [here](https://github.com/fuse-open/fuselibs/blob/a8a9cb7fe9cff8a4e1fe3dbeb472ba764313db6a/Source/Fuse.ImageTools/Android/Image.java#L141) and [here](https://github.com/fuse-open/fuselibs/blob/a8a9cb7fe9cff8a4e1fe3dbeb472ba764313db6a/Source/Fuse.ImageTools/Android/Image.java#L151) where Uri has to replace with fileprovider

I see user also reporting share module is crashing mention in [here](https://forums.fusetools.com/t/issue-camera-crash/6391/6). maybe it is relating with Uri stuff same as here

**Comment by ckarmy** [comment] 2019-01-30 13:23
Yes, Share module and Camera module crash. Like @ichan-mb said this is solved making a 'hack' adding a file_path and adding some lines in the manifest.

You can reproduce the crash in this app reproduction:

```
<App>
	<JavaScript>
		var camera = require('FuseJS/Camera');

		function takePicture() {
			camera.takePicture(640,480).then(function(image) {
			    //Do things with image here
			}).catch(function(error) {
			    //Something went wrong, see error for details
			});
		}

		module.exports = {
			takePicture: takePicture
		};
	</JavaScript>

	<StackPanel Alignment="Center" Padding="40">
		<Button Text="Take picture" Clicked="{takePicture}" />
	</StackPanel>
</App>
```

To solve this you need to create the file_path file:

```
<?xml version="1.0" encoding="utf-8"?>
<paths xmlns:android="http://schemas.android.com/apk/res/android">
    <external-cache-path name="myexternalimages" path="/Shared" />
    <external-files-path  name="myexternalimages2" path="/Pictures" />
    <external-path
        name="external_files"
        path="." />
    <root-path
        name="external_files"
        path="/storage/" />
</paths>
```

and add to the manifest file this:

```
<provider
	android:name="android.support.v4.content.FileProvider"
	android:authorities="{NAMESPACE}.fileprovider"
	android:exported="false"
	android:grantUriPermissions="true">
	<meta-data
		android:name="android.support.FILE_PROVIDER_PATHS"
		android:resource="@xml/file_paths"></meta-data>
</provider>
```

**Comment by AndrewEQ** [comment] 2019-01-30 13:40
Thanks for the assistance guys, I'm busy having a look at the Share and Camera module for y'all.

**Comment by kusma** [comment] 2019-01-31 13:10
So uhm, this is clearly a duplicate of #932, so let's keep the discussion there...

**Closed by kusma** 2019-01-31 13:10 UTC
